# Generated by Django 5.2.8 on 2026-04-01 23:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.PositiveIntegerField(default=0, verbose_name='Total ventas')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Ingresos totales')),
                ('pending_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Ganancias pendientes')),
                ('released_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Ganancias liberadas')),
                ('unique_listeners', models.PositiveIntegerField(default=0, verbose_name='Oyentes únicos')),
                ('top_song_id', models.IntegerField(blank=True, null=True, verbose_name='ID de canción más vendida')),
                ('top_song_title', models.CharField(blank=True, max_length=255, verbose_name='Canción más vendida')),
                ('top_song_sales', models.PositiveIntegerField(default=0, verbose_name='Ventas de canción top')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Último cálculo')),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_stats', to=settings.AUTH_USER_MODEL, verbose_name='Artista')),
            ],
            options={
                'verbose_name': 'Estadísticas del artista',
                'verbose_name_plural': 'Estadísticas de artistas',
            },
        ),
        migrations.CreateModel(
            name='AudienceInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('country', 'Por país'), ('city', 'Por ciudad'), ('hour', 'Por hora del día'), ('device', 'Por dispositivo')], max_length=20, verbose_name='Tipo de insight')),
                ('key', models.CharField(max_length=100, verbose_name='Clave')),
                ('value', models.CharField(max_length=255, verbose_name='Valor')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Conteo')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Porcentaje')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_insights', to=settings.AUTH_USER_MODEL, verbose_name='Artista')),
            ],
            options={
                'verbose_name': 'Insight de audiencia',
                'verbose_name_plural': 'Insights de audiencia',
                'ordering': ['-count'],
                'unique_together': {('artist', 'insight_type', 'key')},
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='Ventas del día')),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Ingresos del día')),
                ('unique_listeners', models.PositiveIntegerField(default=0, verbose_name='Oyentes únicos del día')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL, verbose_name='Artista')),
            ],
            options={
                'verbose_name': 'Estadística diaria',
                'verbose_name_plural': 'Estadísticas diarias',
                'ordering': ['-date'],
                'unique_together': {('artist', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SongStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.IntegerField(verbose_name='ID de canción')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='Ventas')),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Ingresos')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('plays_count', models.PositiveIntegerField(default=0, verbose_name='Reproducciones')),
                ('trend', models.CharField(choices=[('up', '⬆️ Subiendo'), ('down', '⬇️ Bajando'), ('stable', '➡️ Estable'), ('new', '🆕 Nueva')], default='stable', max_length=20, verbose_name='Tendencia')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_stats', to=settings.AUTH_USER_MODEL, verbose_name='Artista')),
            ],
            options={
                'verbose_name': 'Estadística de canción',
                'verbose_name_plural': 'Estadísticas de canciones',
                'ordering': ['-sales_count'],
                'unique_together': {('artist', 'song_id')},
            },
        ),
    ]
