# Generated by Django 5.2.8 on 2026-04-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiststats',
            name='top_song_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Canción más vendida'),
        ),
    ]
