# Generated by Django 5.2.8 on 2026-04-01 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('musica', '0002_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='uservisit',
            options={'ordering': ['-fecha_visita'], 'verbose_name': 'Visita de usuario', 'verbose_name_plural': 'Visitas de usuarios'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_withdraw',
            field=models.BooleanField(default=False, help_text='Solo usuarios verificados pueden retirar dinero', verbose_name='Puede retirar dinero'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('GQ', 'Guinea Ecuatorial'), ('ES', 'España'), ('FR', 'Francia'), ('US', 'Estados Unidos'), ('IT', 'Italia'), ('PT', 'Portugal'), ('CM', 'Camerún'), ('GA', 'Gabón'), ('CG', 'Congo'), ('GB', 'Reino Unido'), ('DE', 'Alemania'), ('OTHER', 'Otro')], default='GQ', help_text='País de residencia (determina la moneda)', max_length=5, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Usuario verificado con badge azul', verbose_name='Verificado'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='es_recurrente',
            field=models.BooleanField(default=False, verbose_name='¿Es recurrente?'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='fecha_visita',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de visita'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0.0', verbose_name='Dirección IP'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='latitud',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='longitud',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='navegador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Navegador'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='proveedor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor ISP'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='sistema_operativo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema Operativo'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='url_referencia',
            field=models.URLField(blank=True, null=True, verbose_name='URL de referencia'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='musica_cust_email_992ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone'], name='musica_cust_phone_11518d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['country'], name='musica_cust_country_307f99_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_verified'], name='musica_cust_is_veri_1dd318_idx'),
        ),
        migrations.AddIndex(
            model_name='uservisit',
            index=models.Index(fields=['fecha_visita'], name='musica_user_fecha_v_77a4f4_idx'),
        ),
        migrations.AddIndex(
            model_name='uservisit',
            index=models.Index(fields=['pais'], name='musica_user_pais_39d126_idx'),
        ),
        migrations.AddIndex(
            model_name='uservisit',
            index=models.Index(fields=['user'], name='musica_user_user_id_de1b48_idx'),
        ),
    ]
