# Generated by Django 5.2.8 on 2026-04-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0003_alter_customuser_options_alter_uservisit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Términos aceptados'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aceptación de términos'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='Dirección IP'),
        ),
    ]
