# Generated by Django 5.2.8 on 2026-04-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0004_customuser_birth_date_customuser_gender_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='musica_cust_country_307f99_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, help_text='País de residencia (ej: Guinea Ecuatorial, España, etc.)', max_length=100, null=True, verbose_name='País'),
        ),
    ]
