# Generated by Django 5.2.13 on 2026-04-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('musica', '0005_remove_customuser_musica_cust_country_307f99_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_public',
            field=models.BooleanField(default=True, help_text='¿Perfil visible públicamente para buscadores y listados?', verbose_name='Perfil público'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único para la URL del perfil (ej: alfa-cohiba)', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['slug'], name='musica_cust_slug_12072a_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_public'], name='musica_cust_is_publ_a4c34c_idx'),
        ),
    ]
