# Generated by Django 5.2.13 on 2026-04-22 01:01
# VERSIÓN CORREGIDA - Genera slugs antes de aplicar unique

from django.db import migrations, models
from django.utils.text import slugify


def generate_unique_slugs(apps, schema_editor):
    """
    Genera slugs únicos para todos los usuarios existentes.
    Se ejecuta DESPUÉS de añadir el campo slug pero ANTES de hacerlo único.
    """
    CustomUser = apps.get_model('musica', 'CustomUser')
    
    print(f"\n🚀 Generando slugs para {CustomUser.objects.count()} usuarios...")
    
    # Primero, asignar slugs base a todos los usuarios
    for user in CustomUser.objects.all():
        base = user.full_name or user.username
        slug = slugify(base)
        
        # Si el slug está vacío, usar el username
        if not slug:
            slug = slugify(user.username or f"user-{user.id}")
        
        # Si sigue vacío, usar el ID
        if not slug:
            slug = f"user-{user.id}"
        
        user.slug = slug
        user.save(update_fields=['slug'])
    
    # Luego, resolver duplicados (usuarios con mismo nombre)
    seen_slugs = set()
    duplicates_fixed = 0
    
    for user in CustomUser.objects.all().order_by('date_joined'):
        original_slug = user.slug
        counter = 1
        
        while user.slug in seen_slugs:
            user.slug = f"{original_slug}-{counter}"
            counter += 1
            duplicates_fixed += 1
        
        seen_slugs.add(user.slug)
        
        if user.slug != original_slug:
            user.save(update_fields=['slug'])
    
    print(f"✅ Slugs generados. {duplicates_fixed} duplicados resueltos.")


def reverse_slugs(apps, schema_editor):
    """Reversión: no hace nada, los campos se eliminarán."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('musica', '0005_remove_customuser_musica_cust_country_307f99_idx_and_more'),
    ]

    operations = [
        # 1. Añadir campo is_public (no depende de slug)
        migrations.AddField(
            model_name='customuser',
            name='is_public',
            field=models.BooleanField(
                default=True,
                help_text='¿Perfil visible públicamente para buscadores y listados?',
                verbose_name='Perfil público'
            ),
        ),
        
        # 2. Añadir campo updated_at
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                verbose_name='Última actualización'
            ),
        ),
        
        # 3. Añadir campo slug SIN unique (temporalmente)
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(
                blank=True,
                default='',  # ← Importante: valor por defecto
                help_text='Identificador único para la URL del perfil (ej: alfa-cohiba)',
                max_length=255,
                # unique=True,  ← QUITADO temporalmente
            ),
        ),
        
        # 4. 🆕 Generar slugs únicos para todos los usuarios
        migrations.RunPython(
            generate_unique_slugs,
            reverse_code=reverse_slugs,
        ),
        
        # 5. Ahora SÍ, hacer el campo slug único
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(
                blank=True,
                help_text='Identificador único para la URL del perfil (ej: alfa-cohiba)',
                max_length=255,
                unique=True,  # ← AHORA SÍ aplicamos unique
            ),
        ),
        
        # 6. Añadir índices
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['slug'], name='musica_cust_slug_12072a_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_public'], name='musica_cust_is_publ_a4c34c_idx'),
        ),
    ]