# Generated by Django 5.2.8 on 2025-11-16 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('duration_played', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('avatar_key', models.CharField(blank=True, max_length=500, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('favorite_genres', models.JSONField(blank=True, default=list)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('songs_uploaded', models.PositiveIntegerField(default=0)),
                ('total_listening_time', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='commentreaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='download',
            options={'ordering': ['-downloaded_at']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='musicevent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='song',
            name='file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('laugh', 'Laugh'), ('sad', 'Sad'), ('angry', 'Angry')], default='like', max_length=10),
        ),
        migrations.AddField(
            model_name='download',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musicevent',
            name='event_type',
            field=models.CharField(choices=[('concert', 'Concierto'), ('festival', 'Festival'), ('party', 'Fiesta'), ('workshop', 'Taller'), ('other', 'Otro')], default='concert', max_length=20),
        ),
        migrations.AddField(
            model_name='musicevent',
            name='image_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='musicevent',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musicevent',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='musicevent',
            name='ticket_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musicevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='musicevent',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='file_key',
            field=models.CharField(default='songs/temp_file', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='image_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='song',
            name='plays_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='song',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='download',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='api2.song'),
        ),
        migrations.AlterField(
            model_name='like',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api2.song'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='api2_commen_created_96dbfe_idx'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['downloaded_at'], name='api2_downlo_downloa_146469_idx'),
        ),
        migrations.AddIndex(
            model_name='musicevent',
            index=models.Index(fields=['event_date'], name='api2_musice_event_d_6351a6_idx'),
        ),
        migrations.AddIndex(
            model_name='musicevent',
            index=models.Index(fields=['is_active'], name='api2_musice_is_acti_f011be_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['artist'], name='api2_song_artist_0c7ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['genre'], name='api2_song_genre_b56425_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['created_at'], name='api2_song_created_ca5038_idx'),
        ),
        migrations.AddField(
            model_name='playhistory',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to='api2.song'),
        ),
        migrations.AddField(
            model_name='playhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='playhistory',
            index=models.Index(fields=['played_at'], name='api2_playhi_played__89baaf_idx'),
        ),
    ]
