# Generated by Django 5.2.8 on 2025-11-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0002_playhistory_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file_key',
            field=models.CharField(default='songs/temp_file', max_length=500, unique=True),
        ),
    ]
