# Generated by Django 5.2.8 on 2026-01-24 23:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0003_fix_song_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_uploads_count', models.PositiveIntegerField(default=0)),
                ('daily_uploads_size', models.BigIntegerField(default=0)),
                ('daily_uploads_reset_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pending_uploads_count', models.PositiveIntegerField(default=0)),
                ('pending_uploads_size', models.BigIntegerField(default=0)),
                ('total_uploads_count', models.PositiveIntegerField(default=0)),
                ('total_uploads_size', models.BigIntegerField(default=0)),
                ('max_daily_uploads', models.PositiveIntegerField(default=50)),
                ('max_daily_size', models.BigIntegerField(default=524288000)),
                ('max_file_size', models.BigIntegerField(default=104857600)),
                ('max_total_storage', models.BigIntegerField(default=5368709120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['daily_uploads_reset_at'], name='api2_upload_daily_u_26557b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(blank=True, default='', max_length=100)),
                ('original_file_name', models.CharField(max_length=255)),
                ('file_key', models.CharField(max_length=500)),
                ('image_key', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente - URL generada'), ('uploaded', 'Subido a R2 - Esperando confirmación'), ('confirmed', 'Confirmado - En procesamiento'), ('processing', 'Procesando en background'), ('ready', 'Completado - Canción lista'), ('failed', 'Fallido'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_sessions', to='api2.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='api2_upload_user_id_203f6d_idx'), models.Index(fields=['status', 'expires_at'], name='api2_upload_status_e941a2_idx'), models.Index(fields=['created_at'], name='api2_upload_created_cc306c_idx'), models.Index(fields=['confirmed'], name='api2_upload_confirm_083c7b_idx')],
            },
        ),
    ]
