# Generated by Django 5.2.2 on 2026-02-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0004_uploadquota_uploadsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='songs/audio/'),
        ),
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='songs/covers/'),
        ),
        migrations.AddField(
            model_name='song',
            name='file_format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
