# Generated by Django 5.2.8 on 2026-03-11 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0005_song_audio_file_song_cover_image_song_file_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='download_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='download',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['download_token'], name='api2_downlo_downloa_9c4dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['is_confirmed'], name='api2_downlo_is_conf_4c80e3_idx'),
        ),
    ]
