# Generated by Django 5.2.8 on 2026-03-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0007_fix_download_token_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='download_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
