# Generated by Django 5.2.8 on 2026-03-23 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0008_alter_download_download_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='api2_commen_created_96dbfe_idx',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['song', '-created_at'], name='comment_song_created_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='comment_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created_at'], name='comment_created_idx'),
        ),
    ]
