# Generated by Django 5.2.8 on 2026-04-01 02:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0009_remove_comment_api2_commen_created_96dbfe_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='commentreaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reacción', 'verbose_name_plural': 'Reacciones'},
        ),
        migrations.AlterModelOptions(
            name='download',
            options={'ordering': ['-downloaded_at'], 'verbose_name': 'Descarga', 'verbose_name_plural': 'Descargas'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at'], 'verbose_name': 'Me gusta', 'verbose_name_plural': 'Me gusta'},
        ),
        migrations.AlterModelOptions(
            name='musicevent',
            options={'ordering': ['-event_date'], 'verbose_name': 'Evento musical', 'verbose_name_plural': 'Eventos musicales'},
        ),
        migrations.AlterModelOptions(
            name='playhistory',
            options={'ordering': ['-played_at'], 'verbose_name': 'Historial de reproducción', 'verbose_name_plural': 'Historial de reproducciones'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-created_at'], 'verbose_name': 'Canción', 'verbose_name_plural': 'Canciones'},
        ),
        migrations.AlterModelOptions(
            name='uploadquota',
            options={'verbose_name': 'Cuota de subida', 'verbose_name_plural': 'Cuotas de subida'},
        ),
        migrations.AlterModelOptions(
            name='uploadsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sesión de subida', 'verbose_name_plural': 'Sesiones de subida'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de usuario', 'verbose_name_plural': 'Perfiles de usuario'},
        ),
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.CharField(choices=[('standard', 'Estándar'), ('hit', 'Éxito/Sencillo popular'), ('premium', 'Premium'), ('classic', 'Clásico')], db_index=True, default='standard', help_text='Define el precio de la canción (según acuerdo plataforma-gremio)', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='song',
            name='is_purchasable',
            field=models.BooleanField(default=True, help_text='Si está activo, los usuarios pueden comprar esta canción', verbose_name='Disponible para compra'),
        ),
        migrations.AddField(
            model_name='song',
            name='last_purchased_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Última compra'),
        ),
        migrations.AddField(
            model_name='song',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Veces comprada'),
        ),
        migrations.AddField(
            model_name='song',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='Ingresos totales'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='¿Editado?'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api2.song', verbose_name='Canción'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api2.comment', verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('laugh', 'Laugh'), ('sad', 'Sad'), ('angry', 'Angry')], default='like', max_length=10, verbose_name='Tipo de reacción'),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='download',
            name='download_token',
            field=models.CharField(blank=True, max_length=64, verbose_name='Token de descarga'),
        ),
        migrations.AlterField(
            model_name='download',
            name='downloaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha descarga'),
        ),
        migrations.AlterField(
            model_name='download',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP'),
        ),
        migrations.AlterField(
            model_name='download',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='¿Confirmada?'),
        ),
        migrations.AlterField(
            model_name='download',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='api2.song', verbose_name='Canción'),
        ),
        migrations.AlterField(
            model_name='download',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='download',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='like',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api2.song', verbose_name='Canción'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='musicevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='musicevent',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='musicevent',
            name='event_date',
            field=models.DateTimeField(verbose_name='Fecha del evento'),
        ),
        migrations.AlterField(
            model_name='musicevent',
            name='event_type',
            field=models.CharField(choices=[('concert', 'Concierto'), ('festival', 'Festival'), ('party', 'Fiesta'), ('workshop', 'Taller'), ('other', 'Otro')], default='concert', max_length=20, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='musicevent',
            name='image_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Clave R2 (imagen)'),
        ),
        migrations.AlterField(
            model_name='musicevent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='musicevent',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
        migrations.AlterField(
            model_name='musicevent',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='musicevent',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='musicevent',
            name='ticket_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de entradas'),
        ),
        migrations.AlterField(
            model_name='musicevent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='musicevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='musicevent',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar específico'),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='duration_played',
            field=models.IntegerField(default=0, verbose_name='Segundos reproducidos'),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP'),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='played_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha reproducción'),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to='api2.song', verbose_name='Canción'),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(help_text='Nombre artístico que se mostrará', max_length=255, verbose_name='Artista'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='songs/audio/', verbose_name='Archivo de audio'),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='songs/covers/', verbose_name='Imagen de portada'),
        ),
        migrations.AlterField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='song',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Descargas'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file_format',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file_key',
            field=models.CharField(default='songs/temp_file', max_length=500, unique=True, verbose_name='Clave R2 (audio)'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tamaño del archivo'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(max_length=100, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Clave R2 (imagen)'),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Si es privada, solo el artista puede verla', verbose_name='Pública'),
        ),
        migrations.AlterField(
            model_name='song',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Me gusta'),
        ),
        migrations.AlterField(
            model_name='song',
            name='plays_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Reproducciones'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='song',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='song',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que subió la canción (recibe el 80% de las ventas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_songs', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AlterField(
            model_name='uploadquota',
            name='daily_uploads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Subidas diarias'),
        ),
        migrations.AlterField(
            model_name='uploadquota',
            name='daily_uploads_reset_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Reset diario'),
        ),
        migrations.AlterField(
            model_name='uploadquota',
            name='daily_uploads_size',
            field=models.BigIntegerField(default=0, verbose_name='Tamaño subido hoy'),
        ),
        migrations.AlterField(
            model_name='uploadquota',
            name='max_daily_size',
            field=models.BigIntegerField(default=524288000, verbose_name='Límite tamaño diario'),
        ),
        migrations.AlterField(
            model_name='uploadquota',
            name='max_daily_uploads',
            field=models.PositiveIntegerField(default=50, verbose_name='Límite subidas diarias'),
        ),
        migrations.AlterField(
            model_name='uploadquota',
            name='max_file_size',
            field=models.BigIntegerField(default=104857600, verbose_name='Tamaño máximo por archivo'),
        ),
        migrations.AlterField(
            model_name='uploadquota',
            name='max_total_storage',
            field=models.BigIntegerField(default=5368709120, verbose_name='Almacenamiento total máximo'),
        ),
        migrations.AlterField(
            model_name='uploadquota',
            name='pending_uploads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Subidas pendientes'),
        ),
        migrations.AlterField(
            model_name='uploadquota',
            name='pending_uploads_size',
            field=models.BigIntegerField(default=0, verbose_name='Tamaño pendiente'),
        ),
        migrations.AlterField(
            model_name='uploadquota',
            name='total_uploads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Total subidas'),
        ),
        migrations.AlterField(
            model_name='uploadquota',
            name='total_uploads_size',
            field=models.BigIntegerField(default=0, verbose_name='Total tamaño'),
        ),
        migrations.AlterField(
            model_name='uploadquota',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='uploadquota',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_quota', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha completado'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmado'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha confirmación'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Fecha expiración'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='file_key',
            field=models.CharField(max_length=500, verbose_name='Clave R2'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='Nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='file_size',
            field=models.BigIntegerField(verbose_name='Tamaño del archivo'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='file_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo MIME'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='image_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Clave R2 (imagen)'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadatos'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='original_file_name',
            field=models.CharField(max_length=255, verbose_name='Nombre original'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_sessions', to='api2.song', verbose_name='Canción creada'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente - URL generada'), ('uploaded', 'Subido a R2 - Esperando confirmación'), ('confirmed', 'Confirmado - En procesamiento'), ('processing', 'Procesando en background'), ('ready', 'Completado - Canción lista'), ('failed', 'Fallido'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='status_message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de estado'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Clave R2 (avatar)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_genres',
            field=models.JSONField(blank=True, default=list, verbose_name='Géneros favoritos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Notificaciones activadas'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='songs_uploaded',
            field=models.PositiveIntegerField(default=0, verbose_name='Canciones subidas'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_listening_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Tiempo total escuchado (segundos)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['category', 'is_purchasable'], name='api2_song_categor_0bcdab_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['uploaded_by'], name='api2_song_uploade_09089c_idx'),
        ),
    ]
