# Generated by Django 5.2.13 on 2026-04-25 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0010_alter_comment_options_alter_commentreaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.CharField(blank=True, max_length=500)),
                ('playlist_type', models.CharField(choices=[('temporal', 'Temporal (actualización frecuente)'), ('generica', 'Genérica (por género/estilo)'), ('nicho', 'Nicho (específico, localizado)'), ('mood', 'Por estado de ánimo'), ('promocional', 'Promocional / Patrocinada')], default='generica', max_length=20)),
                ('update_frequency', models.CharField(choices=[('hourly', 'Cada hora'), ('daily', 'Diaria'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('never', 'Nunca (manual)')], default='weekly', max_length=20)),
                ('algorithm', models.CharField(choices=[('manual', 'Selección manual por staff'), ('trending', 'Tendencias (más populares)'), ('new_releases', 'Nuevos lanzamientos'), ('top_genre', 'Top por género'), ('hybrid', 'Híbrido (staff + algoritmo)')], default='manual', max_length=20)),
                ('min_songs', models.PositiveIntegerField(default=10)),
                ('max_songs', models.PositiveIntegerField(default=50)),
                ('target_genres', models.JSONField(blank=True, default=list)),
                ('target_country', models.CharField(blank=True, max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('song_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_streams', models.PositiveIntegerField(default=0)),
                ('unique_listeners', models.PositiveIntegerField(default=0)),
                ('saves_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_curated_playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Playlist curada',
                'verbose_name_plural': 'Playlists curadas',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CuratedPlaylistAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_streams', models.PositiveIntegerField(default=0)),
                ('unique_listeners', models.PositiveIntegerField(default=0)),
                ('avg_completion_rate', models.FloatField(default=0.0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('saves_count', models.PositiveIntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='api2.curatedplaylist')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CuratedPlaylistSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='api2.curatedplaylist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_curated_playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuratedPlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_curated_songs', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs_relation', to='api2.curatedplaylist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_curated_playlists', to='api2.song')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='curatedplaylist',
            index=models.Index(fields=['is_active', 'playlist_type'], name='api2_curate_is_acti_29bf61_idx'),
        ),
        migrations.AddIndex(
            model_name='curatedplaylist',
            index=models.Index(fields=['slug'], name='api2_curate_slug_879ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='curatedplaylist',
            index=models.Index(fields=['-priority'], name='api2_curate_priorit_3cac8c_idx'),
        ),
        migrations.AddIndex(
            model_name='curatedplaylist',
            index=models.Index(fields=['featured', 'is_active'], name='api2_curate_feature_50a649_idx'),
        ),
        migrations.AddIndex(
            model_name='curatedplaylistanalytics',
            index=models.Index(fields=['playlist', 'date'], name='api2_curate_playlis_a709b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='curatedplaylistanalytics',
            unique_together={('playlist', 'date')},
        ),
        migrations.AddIndex(
            model_name='curatedplaylistsave',
            index=models.Index(fields=['user'], name='api2_curate_user_id_69539f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='curatedplaylistsave',
            unique_together={('playlist', 'user')},
        ),
        migrations.AddIndex(
            model_name='curatedplaylistsong',
            index=models.Index(fields=['playlist', 'position'], name='api2_curate_playlis_11d860_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='curatedplaylistsong',
            unique_together={('playlist', 'song')},
        ),
    ]
