# Generated by Django 5.2.8 on 2026-04-01 02:49

import django.core.validators
import django.db.models.deletion
import wallet.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo que puede gastar ahora', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Saldo disponible')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo retenido (esperando liberación a artista)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Saldo pendiente')),
                ('total_deposited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total depositado')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total gastado')),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total retirado (artistas)')),
                ('currency', models.CharField(choices=[('XAF', 'Franco CFA (XAF)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dólar USD')], default='XAF', max_length=3, validators=[wallet.validators.validate_currency], verbose_name='Moneda')),
                ('is_active', models.BooleanField(default=True, help_text='Si está inactivo, no se pueden realizar transacciones', verbose_name='Activo')),
                ('custom_daily_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Límite diario personalizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Monedero',
                'verbose_name_plural': 'Monederos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, editable=False, max_length=32, unique=True, verbose_name='Referencia')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('-999999.00'))], verbose_name='Monto')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Saldo anterior')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Saldo posterior')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Recarga'), ('purchase', 'Compra'), ('refund', 'Reembolso'), ('release', 'Liberación a artista'), ('gift_sent', 'Regalo enviado'), ('gift_received', 'Regalo recibido'), ('adjustment', 'Ajuste manual'), ('fee', 'Comisión plataforma'), ('withdrawal', 'Retiro')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('failed', 'Fallida'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], db_index=True, default='completed', max_length=20, verbose_name='Estado')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional: song_id, artist_id, etc.', verbose_name='Metadatos')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha creación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.wallet', verbose_name='Monedero')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[wallet.validators.validate_positive_amount, wallet.validators.validate_min_deposit], verbose_name='Monto')),
                ('currency', models.CharField(choices=[('XAF', 'Franco CFA (XAF)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dólar USD')], default='XAF', max_length=3, verbose_name='Moneda')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='¿Usado?')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha uso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha expiración')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_codes', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_codes', to=settings.AUTH_USER_MODEL, verbose_name='Usado por')),
            ],
            options={
                'verbose_name': 'Código de recarga',
                'verbose_name_plural': 'Códigos de recarga',
                'indexes': [models.Index(fields=['code', 'is_used'], name='wallet_depo_code_4e4435_idx'), models.Index(fields=['expires_at'], name='wallet_depo_expires_5d8581_idx')],
            },
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto retenido')),
                ('release_days', models.PositiveIntegerField(default=7, verbose_name='Días para liberación')),
                ('release_date', models.DateTimeField(db_index=True, verbose_name='Fecha de liberación')),
                ('is_released', models.BooleanField(db_index=True, default=False, verbose_name='¿Liberado?')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha liberación')),
                ('reason', models.CharField(choices=[('song_purchase', 'Compra de canción'), ('album_purchase', 'Compra de álbum'), ('event_ticket', 'Venta de entrada'), ('merch_sale', 'Venta de merchandising'), ('gift', 'Regalo')], default='song_purchase', max_length=50, verbose_name='Motivo')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to=settings.AUTH_USER_MODEL, verbose_name='Artista')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_holds', to=settings.AUTH_USER_MODEL, verbose_name='Liberado por')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hold', to='wallet.transaction', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Retención',
                'verbose_name_plural': 'Retenciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['artist', 'is_released'], name='wallet_hold_artist__2fd868_idx'), models.Index(fields=['release_date', 'is_released'], name='wallet_hold_release_605a95_idx'), models.Index(fields=['created_at'], name='wallet_hold_created_9ccc82_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user', 'is_active'], name='wallet_wall_user_id_c4bb4a_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['available_balance'], name='wallet_wall_availab_589238_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['created_at'], name='wallet_wall_created_bfe759_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['currency'], name='wallet_wall_currenc_81c38b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'created_at'], name='wallet_tran_wallet__a053af_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='wallet_tran_transac_7fcc7b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='wallet_tran_status_58a2dc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference'], name='wallet_tran_referen_f4b8af_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_by'], name='wallet_tran_created_7fb40b_idx'),
        ),
    ]
