# Generated by Django 5.2.8 on 2026-04-01 12:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del local')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(choices=[('GQ', 'Guinea Ecuatorial'), ('ES', 'España'), ('FR', 'Francia'), ('US', 'Estados Unidos')], default='GQ', max_length=2, verbose_name='País')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text='Ej: {"monday": "9:00-18:00", "tuesday": "9:00-18:00"}', verbose_name='Horario de atención')),
                ('coordinates', models.JSONField(blank=True, default=dict, help_text='Ej: {"lat": 3.7523, "lng": 8.7737}', verbose_name='Coordenadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Ubicación física',
                'verbose_name_plural': 'Ubicaciones físicas',
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['city', 'country'], name='wallet_phys_city_e9010a_idx'), models.Index(fields=['is_active'], name='wallet_phys_is_acti_95db72_idx')],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_deposit_limit', models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Límite diario de depósitos')),
                ('max_deposit_per_transaction', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Máximo por transacción')),
                ('total_deposits_made', models.PositiveIntegerField(default=0, verbose_name='Total de depósitos realizados')),
                ('total_amount_deposited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto total depositado')),
                ('is_active', models.BooleanField(default=True, help_text='Si está inactivo, no puede realizar recargas', verbose_name='Activo')),
                ('verified', models.BooleanField(default=False, help_text='Agente verificado por administración', verbose_name='Verificado')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='wallet.physicallocation', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='wallet_agen_user_id_637d8e_idx'), models.Index(fields=['location', 'is_active'], name='wallet_agen_locatio_ca4ef8_idx'), models.Index(fields=['verified'], name='wallet_agen_verifie_b30ef5_idx')],
            },
        ),
    ]
