# Generated by Django 5.2.8 on 2026-04-03 16:55

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_physicallocation_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistMuniAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de teléfono Muni')),
                ('is_default', models.BooleanField(default=True, verbose_name='Por defecto')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta Muni Dinero',
                'verbose_name_plural': 'Cuentas Muni Dinero',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DEPOSIT', 'Depósito'), ('PURCHASE', 'Compra'), ('RELEASE', 'Liberación'), ('WITHDRAWAL', 'Retiro'), ('REDEEM_CODE', 'Canje de código')], max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField()),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Clave idempotente')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Registro de idempotencia',
                'verbose_name_plural': 'Registros de idempotencia',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la oficina')),
                ('address', models.TextField(verbose_name='Dirección completa')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('manager_name', models.CharField(max_length=200, verbose_name='Nombre del responsable')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('daily_cash_limit', models.DecimalField(decimal_places=2, default=Decimal('2000000.00'), max_digits=14, verbose_name='Límite diario de efectivo')),
                ('max_withdrawal_per_artist', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=14, verbose_name='Máximo por retiro por artista')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
            },
        ),
        migrations.CreateModel(
            name='OfficeStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='ID de empleado')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('daily_operation_limit', models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), max_digits=14, verbose_name='Límite diario de operaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Personal de oficina',
                'verbose_name_plural': 'Personal de oficinas',
            },
        ),
        migrations.CreateModel(
            name='OfficeWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto bruto')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Comisión')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto neto')),
                ('withdrawal_method', models.CharField(choices=[('cash', 'Efectivo'), ('muni', 'Muni Dinero')], max_length=10, verbose_name='Método')),
                ('muni_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Muni (si aplica)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('id_number_verified', models.CharField(max_length=50, verbose_name='Número de identificación verificado')),
                ('id_type_verified', models.CharField(default='dni', max_length=20, verbose_name='Tipo de identificación')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_signed', models.BooleanField(default=False, verbose_name='Recibo firmado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
            ],
            options={
                'verbose_name': 'Retiro en oficina',
                'verbose_name_plural': 'Retiros en oficina',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('high_frequency', 'Alta frecuencia'), ('unusual_amount', 'Monto inusual'), ('rapid_withdrawal', 'Retiro rápido'), ('multiple_failed', 'Múltiples fallos')], max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Actividad sospechosa',
                'verbose_name_plural': 'Actividades sospechosas',
            },
        ),
        migrations.AddField(
            model_name='wallet',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Para control de concurrencia', verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='total_amount_deposited',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='agent',
            name='total_deposits_made',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicallocation',
            name='coordinates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='physicallocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='physicallocation',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='physicallocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('-999999.00'))], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Estructura esperada: {"song_id": int, "artist_id": int, ...}', verbose_name='Metadatos'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='wallet_tran_created_fb97c1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'transaction_type', 'created_at'], name='wallet_tran_wallet__5faea0_idx'),
        ),
        migrations.AddConstraint(
            model_name='hold',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='hold_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after', django.db.models.expressions.CombinedExpression(models.F('balance_before'), '+', models.F('amount')))), name='transaction_balance_consistency'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', 0)), name='transaction_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('available_balance__gte', 0)), name='wallet_available_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('pending_balance__gte', 0)), name='wallet_pending_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('total_deposited__gte', 0)), name='wallet_total_deposited_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('total_spent__gte', 0)), name='wallet_total_spent_non_negative'),
        ),
        migrations.AddField(
            model_name='artistmuniaccount',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='muni_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idempotencykey',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_record', to='wallet.transaction'),
        ),
        migrations.AddField(
            model_name='idempotencykey',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='wallet.wallet'),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['city', 'is_active'], name='wallet_offi_city_41992b_idx'),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['name'], name='wallet_offi_name_363ac7_idx'),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='wallet.office'),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office_staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officewithdrawal',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Artista'),
        ),
        migrations.AddField(
            model_name='officewithdrawal',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='wallet.office'),
        ),
        migrations.AddField(
            model_name='officewithdrawal',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_withdrawals', to='wallet.officestaff'),
        ),
        migrations.AddField(
            model_name='officewithdrawal',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_withdrawals', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to='wallet.wallet'),
        ),
        migrations.AddIndex(
            model_name='artistmuniaccount',
            index=models.Index(fields=['phone_number'], name='wallet_arti_phone_n_2702f3_idx'),
        ),
        migrations.AddIndex(
            model_name='artistmuniaccount',
            index=models.Index(fields=['artist', 'is_default'], name='wallet_arti_artist__df77d7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='wallet_audi_user_id_4424d9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='wallet_audi_entity__982630_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='wallet_audi_action_fbad95_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['key'], name='wallet_idem_key_e078a3_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['wallet', 'created_at'], name='wallet_idem_wallet__72d199_idx'),
        ),
        migrations.AddIndex(
            model_name='officestaff',
            index=models.Index(fields=['employee_id'], name='wallet_offi_employe_c0fee5_idx'),
        ),
        migrations.AddIndex(
            model_name='officestaff',
            index=models.Index(fields=['office', 'is_active'], name='wallet_offi_office__c98869_idx'),
        ),
        migrations.AddIndex(
            model_name='officewithdrawal',
            index=models.Index(fields=['artist', 'status'], name='wallet_offi_artist__a44891_idx'),
        ),
        migrations.AddIndex(
            model_name='officewithdrawal',
            index=models.Index(fields=['office', 'status'], name='wallet_offi_office__b787ca_idx'),
        ),
        migrations.AddIndex(
            model_name='officewithdrawal',
            index=models.Index(fields=['reference'], name='wallet_offi_referen_168788_idx'),
        ),
        migrations.AddIndex(
            model_name='officewithdrawal',
            index=models.Index(fields=['paid_at'], name='wallet_offi_paid_at_727a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='officewithdrawal',
            index=models.Index(fields=['artist', 'paid_at'], name='wallet_offi_artist__72d5e8_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['user', 'is_reviewed'], name='wallet_susp_user_id_fd1875_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['created_at'], name='wallet_susp_created_0048d0_idx'),
        ),
    ]
