# Generated by Django 5.2.8 on 2026-04-03 19:07

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_artistmuniaccount_auditlog_idempotencykey_office_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='last_cache_date',
            field=models.DateField(blank=True, null=True, verbose_name='Última fecha de cache'),
        ),
        migrations.AddField(
            model_name='office',
            name='today_withdrawn_cached',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total retirado hoy (cache)'),
        ),
        migrations.AddField(
            model_name='officewithdrawal',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Mensaje de error'),
        ),
        migrations.AddField(
            model_name='officewithdrawal',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Clave de idempotencia'),
        ),
        migrations.AddField(
            model_name='officewithdrawal',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='Intentos de reintento'),
        ),
        migrations.AlterField(
            model_name='officewithdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'En proceso'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('reversed', 'Reversado')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='officewithdrawal',
            index=models.Index(fields=['idempotency_key'], name='wallet_offi_idempot_792dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='officewithdrawal',
            index=models.Index(fields=['status', 'requested_at'], name='wallet_offi_status_937424_idx'),
        ),
    ]
