# Generated by Django 5.2.8 on 2026-04-01 23:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(default=dict, help_text='Estructura: {"push": {"purchase": true, ...}, "email": {...}}', verbose_name='Preferencias')),
                ('email_enabled', models.BooleanField(default=False, help_text='Requiere configuración de SMTP', verbose_name='Email habilitado')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push habilitado')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='In-app habilitado')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Inicio silencio nocturno')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Fin silencio nocturno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de notificación',
                'verbose_name_plural': 'Preferencias de notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('purchase', 'Compra de canción'), ('hold_released', 'Hold liberado'), ('new_comment', 'Nuevo comentario'), ('low_balance', 'Saldo bajo'), ('system', 'Notificación del sistema')], db_index=True, max_length=50, verbose_name='Tipo')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional: song_id, amount, click_action, etc.', verbose_name='Metadatos')),
                ('channels', models.JSONField(blank=True, default=dict, help_text='Registro de qué canales se enviaron', verbose_name='Canales enviados')),
                ('read', models.BooleanField(db_index=True, default=False, verbose_name='Leído')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leído el')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'read'], name='notificatio_user_id_878a13_idx'), models.Index(fields=['type', 'created_at'], name='notificatio_type_8e213d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('web', 'Web Push'), ('ios', 'iOS'), ('android', 'Android')], max_length=20, verbose_name='Tipo de dispositivo')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Token de dispositivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional: subscription_info para web push, etc.', verbose_name='Metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Último uso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dispositivo push',
                'verbose_name_plural': 'Dispositivos push',
                'unique_together': {('user', 'token')},
            },
        ),
    ]
